#Logic Error

num_1 = int(input("Give me a number : ")) # typeerror would be not using int
num_2 = int(input("Give me a another number : 3"))

the_sum = num_1 + num_2 #Logic error would be using *

print("The sum is", the_sum)

